require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/savings_rates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SavingsRate. As you add validations to SavingsRate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SavingsRate.create! valid_attributes
      get savings_rates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      savings_rate = SavingsRate.create! valid_attributes
      get savings_rate_url(savings_rate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_savings_rate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      savings_rate = SavingsRate.create! valid_attributes
      get edit_savings_rate_url(savings_rate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SavingsRate" do
        expect {
          post savings_rates_url, params: { savings_rate: valid_attributes }
        }.to change(SavingsRate, :count).by(1)
      end

      it "redirects to the created savings_rate" do
        post savings_rates_url, params: { savings_rate: valid_attributes }
        expect(response).to redirect_to(savings_rate_url(SavingsRate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SavingsRate" do
        expect {
          post savings_rates_url, params: { savings_rate: invalid_attributes }
        }.to change(SavingsRate, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post savings_rates_url, params: { savings_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested savings_rate" do
        savings_rate = SavingsRate.create! valid_attributes
        patch savings_rate_url(savings_rate), params: { savings_rate: new_attributes }
        savings_rate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the savings_rate" do
        savings_rate = SavingsRate.create! valid_attributes
        patch savings_rate_url(savings_rate), params: { savings_rate: new_attributes }
        savings_rate.reload
        expect(response).to redirect_to(savings_rate_url(savings_rate))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        savings_rate = SavingsRate.create! valid_attributes
        patch savings_rate_url(savings_rate), params: { savings_rate: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested savings_rate" do
      savings_rate = SavingsRate.create! valid_attributes
      expect {
        delete savings_rate_url(savings_rate)
      }.to change(SavingsRate, :count).by(-1)
    end

    it "redirects to the savings_rates list" do
      savings_rate = SavingsRate.create! valid_attributes
      delete savings_rate_url(savings_rate)
      expect(response).to redirect_to(savings_rates_url)
    end
  end
end
